<?php

namespace Store\Form;
use Zend\Form\Element;
use Zend\Form\Form;


 class StoreForm extends Form
 {
     public function __construct($name = null)
     {
         // we want to ignore the name passed
         parent::__construct('store');
         $this->setAttribute('method', 'post');
         $this->setAttribute('enctype','multipart/form-data');
         
         $this->add(array(
             'name' => 'id',
             'type' => 'Hidden',
         ));
       
        // $this->add(array(
        //     'name' => 'url',
        //     'type' => 'Text',
        //     'options' => array(
        //         'label' => 'URL',
        //     ),
        //     'attributes' => array(
        //        'class' => 'form-control',
        //     )
        // ));
        

        $code = new Element\Text('code');
        $code->setLabel('Store Code')
              ->setAttribute('id', 'code')
              ->setAttribute('class', 'form-control');
              $this->add($code);
        $name = new Element\Text('name');
        $name->setLabel('Store Name')
              ->setAttribute('id', 'name')
              ->setAttribute('class', 'form-control');
              $this->add($name);

        $desc = new Element\Textarea('description');
        $desc->setLabel('Store Description')
              ->setAttribute('id', 'description')
              ->setAttribute('class', 'form-control');
              $this->add($desc);

        $url = new Element\Url('URL');
        $url->setLabel('Store URL')
              ->setAttribute('id', 'URL')
              ->setAttribute('class', 'form-control');
              $this->add($url);
        
        $this->add([
            'type' => Element\Radio::class,
            'name' => 'type',
            'options' => [
                'label' => 'Store Type',
                'value_options' => [
                    '1' => 'Department',
                    '2' => 'Boutique',
                    '3' => 'Outlet',
                    '4' => 'Flagship',
                    '5' => 'Stockist',
                ]
            ],
        ]);

        $this->add([
            'type' => Element\Checkbox::class,
            'name' => 'stock_import',
            'options' => [
                'label' => 'Stock Import',
                'use_hidden_element' => true,
                'checked_value' => '1',
                'unchecked_value' => '0',
            ],
            'attributes' => [
                 'value' => '1',
            ],
        ]);

        $this->add([
            'type' => Element\Checkbox::class,
            'name' => 'store',
            'options' => [
                'label' => 'Enable Store',
                'use_hidden_element' => true,
                'checked_value' => '1',
                'unchecked_value' => '0',
            ],
            'attributes' => [
                 'value' => '1',
            ],
        ]);


        $country = new Element\Select('country');
        $country->setLabel('Country')
              ->setAttribute('id', 'country')
              ->setAttribute('class', 'form-control');
        $country->setValueOptions([
            "IN" => "India",
            "AD" => "Andorra",
            "AE" => "United Arab Emirates",
            "AF" => "Afghanistan",
            "AG" => "Antigua and Barbuda",
            "AI" => "Anguilla",
            "AL" => "Albania",
            "AM" => "Armenia",
            "AO" => "Angola",
            "AQ" => "Antarctica",
            "AR" => "Argentina",
            "AS" => "American Samoa",
            "AT" => "Austria",
            "AU" => "Australia",
            "AW" => "Aruba",
            "AX" => "Aland Islands",
            "AZ" => "Azerbaijan",
            "BA" => "Bosnia and Herzegovina",
            "BB" => "Barbados",
            "BD" => "Bangladesh",
            "BE" => "Belgium",
            "BF" => "Burkina Faso",
            "BG" => "Bulgaria",
            "BH" => "Bahrain",
            "BI" => "Burundi",
            "BJ" => "Benin",
            "BL" => "Saint Barthelemy",
            "BM" => "Bermuda",
            "BN" => "Brunei Darussalam",
            "BO" => "Bolivia (Plurinational State of)",
            "BQ" => "Bonaire, Sint Eustatius and Saba",
            "BR" => "Brazil",
            "BS" => "Bahamas",
            "BT" => "Bhutan",
            "BV" => "Bouvet Island",
            "BW" => "Botswana",
            "BY" => "Belarus",
            "BZ" => "Belize",
            "CA" => "Canada",
            "CC" => "Cocos (Keeling) Islands",
            "CD" => "Congo (Democratic Republic of the)",
            "CF" => "Central African Republic",
            "CG" => "Congo",
            "CH" => "Switzerland",
            "CI" => "Cote d'Ivoire",
            "CK" => "Cook Islands",
            "CL" => "Chile",
            "CM" => "Cameroon",
            "CN" => "China",
            "CO" => "Colombia",
            "CR" => "Costa Rica",
            "CU" => "Cuba",
            "CV" => "Cabo Verde",
            "CW" => "Curacao",
            "CX" => "Christmas Island",
            "CY" => "Cyprus",
            "CZ" => "Czech Republic",
            "DE" => "Germany",
            "DJ" => "Djibouti",
            "DK" => "Denmark",
            "DM" => "Dominica",
            "DO" => "Dominican Republic",
            "DZ" => "Algeria",
            "EC" => "Ecuador",
            "EE" => "Estonia",
            "EG" => "Egypt",
            "EH" => "Western Sahara",
            "ER" => "Eritrea",
            "ES" => "Spain",
            "ET" => "Ethiopia",
            "FI" => "Finland",
            "FJ" => "Fiji",
            "FK" => "Falkland Islands (Malvinas)",
            "FM" => "Micronesia (Federated States of)",
            "FO" => "Faroe Islands",
            "FR" => "France",
            "GA" => "Gabon",
            "GB" => "United Kingdom of Great Britain",
            "GD" => "Grenada",
            "GE" => "Georgia",
            "GF" => "French Guiana",
            "GG" => "Guernsey",
            "GH" => "Ghana",
            "GI" => "Gibraltar",
            "GL" => "Greenland",
            "GM" => "Gambia",
            "GN" => "Guinea",
            "GP" => "Guadeloupe",
            "GQ" => "Equatorial Guinea",
            "GR" => "Greece",
            "GS" => "South Georgia and the South Sandwich Islands",
            "GT" => "Guatemala",
            "GU" => "Guam",
            "GW" => "Guinea-Bissau",
            "GY" => "Guyana",
            "HK" => "Hong Kong",
            "HM" => "Heard Island and McDonald Islands",
            "HN" => "Honduras",
            "HR" => "Croatia",
            "HT" => "Haiti",
            "HU" => "Hungary",
            "ID" => "Indonesia",
            "IE" => "Ireland",
            "IL" => "Israel",
            "IM" => "Isle of Man",
            "IN" => "India",
            "IO" => "British Indian Ocean Territory",
            "IQ" => "Iraq",
            "IR" => "Iran (Islamic Republic of)",
            "IS" => "Iceland",
            "IT" => "Italy",
            "JE" => "Jersey",
            "JM" => "Jamaica",
            "JO" => "Jordan",
            "JP" => "Japan",
            "KE" => "Kenya",
            "KG" => "Kyrgyzstan",
            "KH" => "Cambodia",
            "KI" => "Kiribati",
            "KM" => "Comoros",
            "KN" => "Saint Kitts and Nevis",
            "KP" => "Korea (Democratic People's Republic of)",
            "KR" => "Korea (Republic of)",
            "KW" => "Kuwait",
            "KY" => "Cayman Islands",
            "KZ" => "Kazakhstan",
            "LA" => "Lao People's Democratic Republic",
            "LB" => "Lebanon",
            "LC" => "Saint Lucia",
            "LI" => "Liechtenstein",
            "LK" => "Sri Lanka",
            "LR" => "Liberia",
            "LS" => "Lesotho",
            "LT" => "Lithuania",
            "LU" => "Luxembourg",
            "LV" => "Latvia",
            "LY" => "Libya",
            "MA" => "Morocco",
            "MC" => "Monaco",
            "MD" => "Moldova (Republic of)",
            "ME" => "Montenegro",
            "MF" => "Saint Martin (French part)",
            "MG" => "Madagascar",
            "MH" => "Marshall Islands",
            "MK" => "Macedonia (the former Yugoslav Republic of)",
            "ML" => "Mali",
            "MM" => "Myanmar",
            "MN" => "Mongolia",
            "MO" => "Macao",
            "MP" => "Northern Mariana Islands",
            "MQ" => "Martinique",
            "MR" => "Mauritania",
            "MS" => "Montserrat",
            "MT" => "Malta",
            "MU" => "Mauritius",
            "MV" => "Maldives",
            "MW" => "Malawi",
            "MX" => "Mexico",
            "MY" => "Malaysia",
            "MZ" => "Mozambique",
            "NA" => "Namibia",
            "NC" => "New Caledonia",
            "NE" => "Niger",
            "NF" => "Norfolk Island",
            "NG" => "Nigeria",
            "NI" => "Nicaragua",
            "NL" => "Netherlands",
            "NO" => "Norway",
            "NP" => "Nepal",
            "NR" => "Nauru",
            "NU" => "Niue",
            "NZ" => "New Zealand",
            "OM" => "Oman",
            "PA" => "Panama",
            "PE" => "Peru",
            "PF" => "French Polynesia",
            "PG" => "Papua New Guinea",
            "PH" => "Philippines",
            "PK" => "Pakistan",
            "PL" => "Poland",
            "PM" => "Saint Pierre and Miquelon",
            "PN" => "Pitcairn",
            "PR" => "Puerto Rico",
            "PS" => "Palestine, State of",
            "PT" => "Portugal",
            "PW" => "Palau",
            "PY" => "Paraguay",
            "QA" => "Qatar",
            "RE" => "Reunion",
            "RO" => "Romania",
            "RS" => "Serbia",
            "RU" => "Russian Federation",
            "RW" => "Rwanda",
            "SA" => "Saudi Arabia",
            "SB" => "Solomon Islands",
            "SC" => "Seychelles",
            "SD" => "Sudan",
            "SE" => "Sweden",
            "SG" => "Singapore",
            "SH" => "Saint Helena, Ascension and Tristan da Cunha",
            "SI" => "Slovenia",
            "SJ" => "Svalbard and Jan Mayen",
            "SK" => "Slovakia",
            "SL" => "Sierra Leone",
            "SM" => "San Marino",
            "SN" => "Senegal",
            "SO" => "Somalia",
            "SR" => "Suriname",
            "SS" => "South Sudan",
            "ST" => "Sao Tome and Principe",
            "SV" => "El Salvador",
            "SX" => "Sint Maarten (Dutch part)",
            "SY" => "Syrian Arab Republic",
            "SZ" => "Swaziland",
            "TC" => "Turks and Caicos Islands",
            "TD" => "Chad",
            "TF" => "French Southern Territories",
            "TG" => "Togo",
            "TH" => "Thailand",
            "TJ" => "Tajikistan",
            "TK" => "Tokelau",
            "TL" => "Timor-Leste",
            "TM" => "Turkmenistan",
            "TN" => "Tunisia",
            "TO" => "Tonga",
            "TR" => "Turkey",
            "TT" => "Trinidad and Tobago",
            "TV" => "Tuvalu",
            "TW" => "Taiwan, Province of China[a]",
            "TZ" => "Tanzania, United Republic of",
            "UA" => "Ukraine",
            "UG" => "Uganda",
            "UM" => "United States Minor Outlying Islands",
            "US" => "United States of America",
            "UY" => "Uruguay",
            "UZ" => "Uzbekistan",
            "VA" => "Holy See",
            "VC" => "Saint Vincent and the Grenadines",
            "VE" => "Venezuela (Bolivarian Republic of)",
            "VG" => "Virgin Islands (British)",
            "VI" => "Virgin Islands (U.S.)",
            "VN" => "Viet Nam",
            "VU" => "Vanuatu",
            "WF" => "Wallis and Futuna",
            "WS" => "Samoa",
            "YE" => "Yemen",
            "YT" => "Mayotte",
            "ZA" => "South Africa",
            "ZM" => "Zambia",
            "ZW" => "Zimbabwe"
            ]);
        $country->setEmptyOption('Select country');
        $this->add($country);
        
        $state = new Element\Select('state');
        $state->setLabel('State/Region')
              ->setAttribute('id', 'state')
              ->setAttribute('class', 'form-control');
        $state->setValueOptions([
            "IN" => "India",

            "08" => "Zanzan",
            "11" => "Zanjān",
            "01" => "Zagrebačka županija",
            "ZAB" => "Zābul",
            "ZAB" => "Zabaykal'skiy kray",
            "06" => "Yên Bái",
            "06" => "Yangon",
            "06" => "Yamagata",
            "10" => "Westmoreland",
            "01" => "Western",
            "WB" => "West Bengal",
            "WAR" => "Warwickshire",
            "WAR" => "Wardak",
            "06" => "Vratsa",
            "07" => "Volyns'ka Oblast'",
            "12" => "Vlorë",
            "10" => "Virovitičko-podravska županija",
            "05" => "Vinnyts'ka Oblast'",
            "01" => "Ville de Kigali",
            "05" => "Villa Clara",
            "11" => "Vieux Fort",
            "05" => "Vidin",
            "12" => "Vevčani",
            "07" => "Vestfold",
            "10" => "Vest-Agder",
            "04" => "Veliko Tarnovo",
            "05" => "Vava'u",
            "11" => "Vasilevo",
            "03" => "Varna",
            "05" => "Varaždinska županija",
            "04" => "Vallée du Bandama",
            "10" => "Valandovo",
            "11" => "Vaduz",
            "UT" => "Uttarakhand",
            "UP" => "Uttar Pradesh",
            "UT" => "Utrecht",
            "UT" => "Utenos Apskritis",
            "UT" => "Utah",
            "URU" => "Uruzgān",
            "UT" => "Upper Takutu-Upper Essequibo",
            "UQ" => "Umm al Qaywayn",
            "07" => "Tuyên Quang",
            "11" => "Tunis",
            "TR" => "Tripura",
            "10" => "Triesenberg",
            "09" => "Triesen",
            "07" => "Trelawny",
            "06" => "Trarza",
            "09" => "Totigi",
            "04" => "Tongatapu",
            "11" => "Tiris Zemmour",
            "11" => "Tiranë",
            "12" => "Tiba",
            "12" => "Tianjin",
            "TG" => "Thurgau",
            "11" => "Terengganu",
            "TN" => "Tennessee",
            "TR" => "Teleorman",
            "08" => "Telemark",
            "TG" => "Telangana",
            "07" => "Tehrān",
            "12" => "Tébessa",
            "03" => "Taza-Al Hoceima-Taounate",
            "05" => "Tanintharyi",
            "01" => "Tanger-Tétouan",
            "TN" => "Tamil Nadu",
            "11" => "Tamanghasset",
            "TAK" => "Takhār",
            "09" => "Tagant",
            "12" => "Tadla-Azilal",
            "07" => "Tabūk",
            "SH" => "Szombathely",
            "SK" => "Szolnok",
            "SK" => "Świętokrzyskie",
            "SK" => "Sud-Kivu",
            "05" => "Sud",
            "10" => "Southern Grenadine Islands",
            "07" => "Southern",
            "05" => "South West",
            "02" => "South Pyongan",
            "05" => "South Hwanghae",
            "08" => "South Hamgyong",
            "04" => "South East",
            "10" => "Soufrière",
            "05" => "Sơn La",
            "03" => "Sisačko-moslavačka županija",
            "SH" => "Širak",
            "SK" => "Sikkim",
            "10" => "Shkodër",
            "SH" => "Shiselweni",
            "SK" => "Shimālī al Baḩrī al Aḩmar",
            "SK" => "Shida Kartli",
            "DN" => "Shamāl Dārfūr",
            "SH" => "Shabwah",
            "SH" => "Shabeellaha Hoose",
            "09" => "Serravalle",
            "11" => "Seoul-teukbyeolsi",
            "12" => "Semnān",
            "10" => "Selangor",
            "SH" => "Schleswig-Holstein",
            "08" => "Schellenberg",
            "SH" => "Schaffhausen",
            "07" => "Schaan",
            "03" => "Savanes",
            "SK" => "Saskatchewan",
            "SAR" => "Saratovskaya oblast'",
            "SAR" => "Sarangani",
            "SAR" => "Sar-e Pul",
            "06" => "Sant Julià de Lòria",
            "SAM" => "Sanma",
            "07" => "Sancti Spíritus",
            "SAM" => "San Martín",
            "07" => "San Marino",
            "11" => "Samut Prakan",
            "SAM" => "Samarskaya oblast'",
            "SAM" => "Samangān",
            "11" => "Saitama",
            "11" => "Saint Thomas",
            "03" => "Saint Thomas",
            "08" => "Saint Philip",
            "10" => "Saint Philip",
            "07" => "Saint Peter",
            "09" => "Saint Peter",
            "11" => "Saint Peter",
            "06" => "Saint Paul",
            "10" => "Saint Paul",
            "09" => "Saint Patrick",
            "06" => "Saint Patrick",
            "05" => "Saint Patrick",
            "08" => "Saint Michael",
            "05" => "Saint Mary",
            "05" => "Saint Mary",
            "08" => "Saint Mark",
            "05" => "Saint Mark",
            "07" => "Saint Luke",
            "07" => "Saint Lucy",
            "06" => "Saint Joseph",
            "06" => "Saint Joseph",
            "04" => "Saint John",
            "05" => "Saint John",
            "05" => "Saint John",
            "04" => "Saint John",
            "04" => "Saint James",
            "08" => "Saint James",
            "03" => "Saint George",
            "03" => "Saint George",
            "04" => "Saint George",
            "03" => "Saint George",
            "04" => "Saint George",
            "11" => "Saint Elizabeth",
            "03" => "Saint David",
            "02" => "Saint David",
            "03" => "Saint David",
            "06" => "Saint Ann",
            "02" => "Saint Andrew",
            "02" => "Saint Andrew",
            "01" => "Saint Andrew",
            "02" => "Saint Andrew",
            "02" => "Saint Andrew",
            "12" => "Sahel",
            "01" => "Sagaing",
            "12" => "Sabah",
            "10" => "Ryanggang",
            "06" => "Ruggell",
            "11" => "Rogaland",
            "RJ" => "Rio de Janeiro",
            "11" => "Redonda",
            "RJ" => "Rajasthan",
            "07" => "Rabat-Salé-Zemmour-Zaer",
            "RK" => "Ra's al Khaymah",
            "01" => "Pyongyang",
            "PB" => "Punjab",
            "PB" => "Punjab",
            "07" => "Pulau Pinang",
            "PY" => "Puducherry",
            "08" => "Primorsko-goranska županija",
            "09" => "Praslin",
            "11" => "Požeško-slavonska županija",
            "04" => "Portland",
            "12" => "Portalegre",
            "12" => "Pool",
            "12" => "Pohjanmaa",
            "11" => "Plateau-Central",
            "05" => "Planken",
            "11" => "Pirkanmaa",
            "01" => "Pinar del Río",
            "12" => "Phnom Penh",
            "09" => "Perlis",
            "08" => "Perak",
            "PAR" => "Parwān",
            "11" => "Paro",
            "PB" => "Paraíba",
            "PAN" => "Panjshayr",
            "PAN" => "Pangasinan",
            "10" => "Panamá Oeste",
            "PIA" => "Paktiyā",
            "PKA" => "Paktīkā",
            "06" => "Pahang",
            "05" => "Pafos",
            "01" => "Østfold",
            "OR" => "Ourense",
            "04" => "Oum el Bouaghi",
            "04" => "Ouest",
            "03" => "Oslo",
            "OR" => "Oromīya",
            "OR" => "Orientale",
            "OR" => "Orhei",
            "OR" => "Oregon",
            "05" => "Ordino",
            "05" => "Oppland",
            "MP" => "Ombella-Mpoko",
            "OR" => "Odisha",
            "11" => "Nzi-Comoé",
            "NUR" => "Nūristān",
            "MP" => "Northern Mariana Islands",
            "05" => "Northern",
            "06" => "North-Western",
            "03" => "North West",
            "03" => "North Pyongan",
            "06" => "North Hwanghae",
            "09" => "North Hamgyong",
            "02" => "North East",
            "10" => "Nord",
            "03" => "Nord",
            "12" => "Nonthaburi",
            "03" => "Niuas",
            "NIM" => "Nīmrōz",
            "12" => "Nikšić",
            "12" => "Nibok",
            "NL" => "Newfoundland and Labrador",
            "05" => "Negeri Sembilan",
            "12" => "Ñeembucú",
            "NAN" => "Nantou",
            "NAN" => "Nangarhār",
            "NL" => "Nālūt",
            "10" => "Najrān",
            "NL" => "Nagaland",
            "MP" => "Mpumalanga",
            "05" => "Moyen-Comoé",
            "08" => "Montegiardino",
            "12" => "Montana",
            "11" => "Mondol Kiri",
            "11" => "Mojkovac",
            "MZ" => "Mizoram",
            "04" => "Miyagi",
            "MN" => "Minnesota",
            "08" => "Micoud",
            "11" => "Meneng",
            "ML" => "Melilla",
            "04" => "Melaka",
            "06" => "Meknès-Tafilalet",
            "MH" => "Mehedinți",
            "ML" => "Meghalaya",
            "MZ" => "Mazowieckie",
            "04" => "Mauren",
            "ML" => "Maule",
            "04" => "Matanzas",
            "MN" => "Matabeleland North",
            "11" => "Marrakech-Tensift-Al Haouz",
            "12" => "Marahoué",
            "MN" => "Manipur",
            "04" => "Mandalay",
            "12" => "Manchester",
            "MN" => "Managua",
            "ML" => "Maluku",
            "ML" => "Malaita",
            "02" => "Makkah",
            "MH" => "Maharashtra",
            "03" => "Magway",
            "MP" => "Madhya Pradesh",
            "MN" => "Ma'ān",
            "LD" => "Łódzkie",
            "09" => "Lusaka",
            "09" => "Luhans'ka Oblast'",
            "04" => "Luapula",
            "11" => "Lovech",
            "LOG" => "Lōgar",
            "11" => "Lisboa",
            "12" => "Lindi",
            "09" => "Ličko-senjska županija",
            "AS" => "Liban-Nord",
            "08" => "Lezhë",
            "02" => "Lemesos",
            "10" => "Leiria",
            "01" => "Lefkosia",
            "10" => "Las Tunas",
            "03" => "Larnaka",
            "10" => "Lappi",
            "02" => "Lào Cai",
            "09" => "Lạng Sơn",
            "LD" => "Lakshadweep",
            "01" => "Lai Châu",
            "01" => "Lagunes",
            "LAG" => "Laguna",
            "03" => "Laghouat",
            "LAG" => "Laghmān",
            "07" => "Lacs",
            "07" => "Laborie",
            "04" => "La Massana",
            "03" => "La Habana",
            "LAG" => "La Guajira",
            "GA" => "La Gare",
            "04" => "L'Oriental",
            "10" => "Kyustendil",
            "09" => "Kymenlaakso",
            "NL" => "KwaZulu-Natal",
            "11" => "Kusini Unguja",
            "10" => "Kusini Pemba",
            "KDZ" => "Kunduz",
            "KNR" => "Kunar",
            "07" => "Kukës",
            "02" => "Krapinsko-zagorska županija",
            "10" => "Kracheh",
            "10" => "Kotor",
            "06" => "Korçë",
            "06" => "Koprivničko-križevačka županija",
            "09" => "Kolašin",
            "KL" => "Klaipėdos Apskritis",
            "01" => "Kingston",
            "09" => "Kilimanjaro",
            "08" => "Kigoma",
            "10" => "Khūzestān",
            "KHO" => "Khōst",
            "KL" => "Kgatleng",
            "08" => "Keski-Suomi",
            "07" => "Keski-Pohjanmaa",
            "06" => "Keryneia",
            "KL" => "Kerala",
            "03" => "Kelantan",
            "02" => "Kedah",
            "12" => "Kayah",
            "KA" => "Katanga",
            "KA" => "Kassalā",
            "07" => "Kaskazini Unguja",
            "06" => "Kaskazini Pemba",
            "KA" => "Karnataka",
            "KA" => "Karlovarský kraj",
            "04" => "Karlovačka županija",
            "09" => "Kardzhali",
            "KA" => "Karbalā'",
            "KA" => "Karas",
            "KA" => "Karak",
            "KAP" => "Kāpīsā",
            "KL" => "Kaolack",
            "06" => "Kanta-Häme",
            "KA" => "Kānim",
            "07" => "Kangwon",
            "KAN" => "Kandahār",
            "KL" => "Kalmykiya, Respublika",
            "KA" => "Kalimantan",
            "05" => "Kainuu",
            "05" => "Kagera",
            "KA" => "Kaffrine",
            "11" => "Kachin",
            "KAB" => "Kābul",
            "KA" => "K'akheti",
            "JH" => "Jubbada Hoose",
            "JOW" => "Jowzjān",
            "01" => "Johor",
            "09" => "Jīzān",
            "JH" => "Jharkhand",
            "JK" => "Jammu and Kashmir",
            "03" => "Iwate",
            "04" => "Iringa",
            "12" => "Inchiri",
            "05" => "Īlām",
            "10" => "Ijuw",
            "08" => "Ibaraki",
            "AJ" => "ʽAjlūn",
            "07" => "Hukusima",
            "HR" => "Hrodzenskaya voblasts'",
            "12" => "Hordaland",
            "11" => "Holguín",
            "01" => "Hokkaidô",
            "02" => "Hodh el Gharbi",
            "01" => "Hodh ech Chargui",
            "HP" => "Himachal Pradesh",
            "08" => "Herceg-Novi",
            "HER" => "Herāt",
            "HEL" => "Helmand",
            "04" => "Hedmark",
            "09" => "Hauts-Bassins",
            "02" => "Haut-Sassandra",
            "HR" => "Haryana",
            "HR" => "Harghita",
            "09" => "Hanover",
            "HP" => "Hải Phòng",
            "06" => "Ḩā'il",
            "02" => "Ha'apai",
            "03" => "Hà Giang",
            "12" => "Gżira",
            "10" => "Gunma",
            "GJ" => "Gujarat",
            "10" => "Guidimaka",
            "11" => "Gudja",
            "09" => "Guarda",
            "06" => "Gros Islet",
            "06" => "Grenadines",
            "12" => "Granma",
            "GA" => "Grande-Anse",
            "08" => "Grand Casablanca",
            "GJ" => "Gorj",
            "04" => "Gorgol",
            "GA" => "Goa",
            "12" => "Glacis",
            "05" => "Gjirokastër",
            "GHO" => "Ghōr",
            "GHA" => "Ghaznī",
            "02" => "Gharb-Chrarda-Beni Hssen",
            "GA" => "Georgia",
            "GA" => "Gasa",
            "03" => "Gamprin",
            "GA" => "Gambēla Hizboch",
            "GA" => "Galicia",
            "GA" => "Galguduud",
            "GA" => "Găgăuzia, Unitatea teritorială autonomă",
            "07" => "Gabrovo",
            "GA" => "Gaborone",
            "10" => "Fontana",
            "09" => "Floriana",
            "05" => "Fiorentino",
            "04" => "Fier",
            "08" => "Fgura",
            "05" => "Fès-Boulemane",
            "FYB" => "Fāryāb",
            "08" => "Faro",
            "FRA" => "Farāh",
            "04" => "Faetano",
            "09" => "Ewa",
            "07" => "Évora",
            "04" => "Etelä-Savo",
            "03" => "Etelä-Pohjanmaa",
            "02" => "Etelä-Karjala",
            "08" => "Est",
            "02" => "Est",
            "04" => "Eşfahān",
            "02" => "Eschen",
            "08" => "Escaldes-Engordany",
            "03" => "Encamp",
            "03" => "Elbasan",
            "03" => "Eastern",
            "DN" => "Đà Nẵng",
            "DU" => "Dushanbe",
            "02" => "Durrës",
            "DU" => "Durazno",
            "DU" => "Dunaújváros",
            "DU" => "Dubayy",
            "DU" => "Dubăsari",
            "10" => "Doukhala-Abda",
            "03" => "Domagnano",
            "03" => "Dodoma",
            "08" => "Dobrich",
            "12" => "Dnipropetrovs'ka Oblast'",
            "DD" => "Dirē Dawa",
            "07" => "Dingli",
            "09" => "Dibër",
            "05" => "Dennery",
            "08" => "Denigomodu",
            "10" => "Denguélé",
            "DL" => "Delhi",
            "DAY" => "Dāykundī",
            "04" => "Dauphin",
            "02" => "Dar es Salaam",
            "07" => "Danilovgrad",
            "DD" => "Daman and Diu",
            "08" => "Dakhlet Nouâdhibou",
            "DN" => "Dadra and Nagar Haveli",
            "08" => "Copperbelt",
            "CT" => "Constanța",
            "CT" => "Connecticut",
            "06" => "Coimbra",
            "06" => "Cienfuegos",
            "08" => "Ciego de Ávila",
            "01" => "Christ Church",
            "CH" => "Choluteca",
            "03" => "Choiseul",
            "CH" => "Choiseul",
            "CH" => "Chobe",
            "02" => "Chlef",
            "02" => "Chiesanuova",
            "12" => "Chhukha",
            "CT" => "Chhattisgarh",
            "01" => "Charlotte",
            "09" => "Chaouia-Ouardigha",
            "CH" => "Chandigarh",
            "CH" => "Champasak",
            "CH" => "Chalatenango",
            "08" => "Chahār Maḩāll va Bakhtīārī",
            "04" => "Chagang",
            "06" => "Cetinje",
            "07" => "Centre-Sud",
            "06" => "Centre-Ouest",
            "05" => "Centre-Nord",
            "04" => "Centre-Est",
            "03" => "Centre",
            "01" => "Central Singapore",
            "11" => "Central",
            "02" => "Central",
            "CT" => "Catalunya",
            "02" => "Castries",
            "05" => "Castelo Branco",
            "02" => "Cascades",
            "11" => "Cascade",
            "CT" => "Capital Territory",
            "04" => "Cao Bằng",
            "CT" => "Cantemir",
            "02" => "Canillo",
            "CT" => "Cần Thơ",
            "09" => "Camagüey",
            "09" => "Butel",
            "06" => "Buskerud",
            "06" => "Būshehr",
            "BR" => "Bururi",
            "02" => "Burgas",
            "05" => "Budva",
            "07" => "Buada",
            "08" => "Brvenica",
            "BR" => "Brokopondo",
            "12" => "Brodsko-posavska županija",
            "BR" => "Briceni",
            "BR" => "Brestskaya voblasts'",
            "05" => "Brakna",
            "BR" => "Brăila",
            "04" => "Bragança",
            "03" => "Braga",
            "10" => "Bouira",
            "11" => "Bouenza",
            "01" => "Boucle du Mouhoun",
            "07" => "Bosilovo",
            "06" => "Bormla",
            "06" => "Borgo Maggiore",
            "06" => "Bogovinje",
            "05" => "Bogdanci",
            "06" => "Boe",
            "09" => "Blida",
            "01" => "Blagoevgrad",
            "07" => "Bjelovarsko-bilogorska županija",
            "04" => "Bitola",
            "07" => "Biskra",
            "05" => "Birżebbuġa",
            "04" => "Birkirkara",
            "03" => "Birgu",
            "12" => "Bingöl",
            "11" => "Bilecik",
            "04" => "Bijelo Polje",
            "BR" => "Bihar",
            "03" => "Berovo",
            "01" => "Berat",
            "03" => "Berane",
            "10" => "Bel Ombre",
            "09" => "Bel Air",
            "06" => "Béjaïa",
            "02" => "Beja",
            "11" => "Beijing",
            "08" => "Béchar",
            "08" => "Beau Vallon",
            "BR" => "Beau Bassin-Rose Hill",
            "05" => "Batna",
            "09" => "Bas-Sassandra",
            "BDG" => "Barking and Dagenham",
            "BR" => "Bari",
            "10" => "Barbuda",
            "02" => "Bar",
            "10" => "Bangkok",
            "BAM" => "Bāmyān",
            "01" => "Balzers",
            "02" => "Balzan",
            "BAL" => "Balkh",
            "10" => "Balıkesir",
            "05" => "Baiti",
            "07" => "Baie Sainte Anne",
            "06" => "Baie Lazare",
            "02" => "Bago",
            "BGL" => "Baghlān",
            "BDG" => "Bādghīs",
            "BDS" => "Badakhshān",
            "01" => "Āz̄arbāyjān-e Sharqī",
            "02" => "Āz̄arbāyjān-e Gharbī",
            "JK" => "Azad Kashmir",
            "AZ" => "Az Zarqā'",
            "07" => "Ayeyarwady",
            "09" => "Aydın",
            "01" => "Aveiro",
            "09" => "Aust-Agder",
            "04" => "Au Cap",
            "01" => "Attard",
            "AS" => "Atlántico Sur",
            "AN" => "Atlántico Norte",
            "AS" => "Asturias, Principado de",
            "AS" => "Assam",
            "03" => "Assaba",
            "SH" => "Ash Sharqīyah",
            "04" => "Ash Sharqīyah",
            "SH" => "Ash Shāriqah",
            "01" => "Arusha",
            "AR" => "Arunachal Pradesh",
            "08" => "Artvin",
            "AR" => "Artigas",
            "AR" => "Artibonite",
            "AR" => "Arta",
            "AR" => "Arkansas",
            "AZ" => "Arizona",
            "AP" => "Arica y Parinacota",
            "12" => "Ariana",
            "03" => "Ardabīl",
            "AR" => "Arbīl",
            "AR" => "Araucanía",
            "AR" => "Ararat",
            "AR" => "Aragón",
            "AR" => "Arad",
            "02" => "Aračinovo",
            "01" => "Ar Riyāḑ",
            "AR" => "Appenzell Ausserrhoden",
            "02" => "Aomori",
            "AN" => "Antofagasta",
            "07" => "Antalya",
            "05" => "Anse Royale",
            "01" => "Anse la Raye",
            "03" => "Anse Etoile",
            "02" => "Anse Boileau",
            "01" => "Anse aux Pins",
            "AN" => "Ansabā",
            "06" => "Ankara",
            "04" => "Anibare",
            "03" => "Anetan",
            "AN" => "Anenii Noi",
            "01" => "Andrijevica",
            "07" => "Andorra la Vella",
            "AN" => "Andijon",
            "AP" => "Andhra Pradesh",
            "AN" => "Andaman and Nicobar Islands",
            "AN" => "Andalucía",
            "AN" => "Anambra",
            "02" => "Anabar",
            "04" => "Ammochostos",
            "AS" => "American Samoa",
            "05" => "Amasya",
            "AP" => "Amapá",
            "10" => "Alto Paraná",
            "AS" => "Ali Sabieh",
            "05" => "Al Qaşīm",
            "MN" => "Al Minyā",
            "03" => "Al Madīnah",
            "12" => "Al Jawf",
            "DU" => "Al Janūbĩ",
            "08" => "Al Ḩudūd ash Shamālīyah",
            "FU" => "Al Fujayrah",
            "11" => "Al Bāḩah",
            "AN" => "Al Anbār",
            "05" => "Akita",
            "02" => "Akershus",
            "AJ" => "Ajaria",
            "01" => "Aiwo",
            "AN" => "Ainaro",
            "01" => "Ahvenanmaan maakunta",
            "04" => "Ağrı",
            "03" => "Afyonkarahisar",
            "01" => "Aerodrom",
            "01" => "Adrar",
            "07" => "Adrar",
            "02" => "Adıyaman",
            "01" => "Adana",
            "01" => "Acquaviva",
            "AZ" => "Abū Z̧aby",
            "06" => "18 Montagnes",
            "01" => "'Eua",
            "AJ" => "'Ajmān"            
            ]);
        $state->setEmptyOption('Select state/region');
        $this->add($state);

        $city = new Element\Text('city');
        $city->setLabel('City')
              ->setAttribute('id', 'city')
              ->setAttribute('class', 'form-control');
              $this->add($city);

        $postal = new Element\Text('postalcode');
        $postal->setLabel('Postal Code')
              ->setAttribute('id', 'postalcode')
              ->setAttribute('class', 'form-control');
              $this->add($postal);
        
        $add1 = new Element\Text('address1');
        $add1->setLabel('Address Line 1')
              ->setAttribute('id', 'address1')
              ->setAttribute('class', 'form-control');
              $this->add($add1);

        $add2 = new Element\Text('address2');
        $add2->setLabel('Address Line 2')
              ->setAttribute('id', 'address2')
              ->setAttribute('class', 'form-control');
              $this->add($add2);

        $this->add([
            'type' => Element\Checkbox::class,
            'name' => 'store_locator',
            'options' => [
                'label' => 'Enable Store Locator',
                'use_hidden_element' => true,
                'checked_value' => '1',
                'unchecked_value' => '0',
            ],
            'attributes' => [
                 'value' => '1',
            ],
        ]);

        $file = new Element\File('store_image');
        $file->setLabel('Image Upload')
             ->setAttribute('id', 'store_image')
             ->setAttribute('class', 'form-control')
             ->setAttribute('accept','image/jpg,image/jpeg');
             $this->add($file);
        
         $this->add(array(
             'name' => 'submit',
             'type' => 'Submit',
             'attributes' => array(
                 'value' => 'Submit',
                 'id' => 'submitbutton',
                 'class' => 'btn btn-primary'
             ),
         ));

     }

    //  public function __construct($name = null, $options = array())
    // {
    //     parent::__construct($name, $options);
    //     $this->addElements();
    // }

    // public function addElements()
    // {
    //     // File Input
    //     $file = new Element\File('image-file');
    //     $file->setLabel('Avatar Image Upload')
    //          ->setAttribute('id', 'image-file');
    //     $this->add($file);
    // }
 }