<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle(' '. $this->translate('StokeInStore'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile('https://unpkg.com/react-bootstrap@next/dist/react-bootstrap.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.21.1/babel.min.js')
            ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/create-react-class/15.7.0/create-react-class.min.js')
            ->prependFile('https://unpkg.com/react-dom/umd/react-dom.production.min.js')
            ->prependFile('https://unpkg.com/react/umd/react.production.min.js')
			->prependFile('https://unpkg.com/axios/dist/axios.min.js')
            ; ?>
			<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top main-nav" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/zf2-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('StokeInStore') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                    <li class="nav-item active">
                        <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Stores') ?></a></li>
                        <li class="nav-item">
                        <a href="<?php echo $this->url('application') ?>/add"><?php echo $this->translate('Add New Store') ?></a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
		<section class="inner-page">
        <div class="container">
            <?php echo $this->content; ?>
         
           
        </div> <!-- /container -->
		</section>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
